services:
  app:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: